name: CI/CD Pipeline for churn prediction

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Installer Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4 : Lancer entraînement
    - name: Run training
      run: |
        python train.py

    # Étape 5 : Lancer les tests
    - name: Run tests
      run: |
        pytest test.py

